CityList/urls.py
from django.urls import path, include
from . import views
from .views import CityDetailView  # Import CityDetailView

urlpatterns = [
    # URLs built for this app specifically
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cities/', views.CityListView, name='cities'),
    path('edit/<int:pk>/', views.edit_city, name='edit-city'),
    path('delete/<int:pk>/', views.delete_city, name='delete-city'),
    path('city/<int:pk>/', CityDetailView.as_view(), name='city-details'),
    path('city-search/', views.city_search_view, name='city-search'),
]


# additional built-in URLs
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

Projects/CityList/code/CityList/urls.py
from django.urls import path
from . import views
from .views import CityDetailView  # Import CityDetailView

urlpatterns = [
    #path function defines a url pattern
    #'' is empty to represent based path to app
    # views.index is the function defined in views.py
    # name='index' parameter is to dynamically create url
    # example in html <a href="{% url 'index' %}">Home</a>.
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cities/', views.CityListView, name='cities'),
    path('city/<int:pk>/', CityDetailView.as_view(), name='city-details'),]


"""
.as_view()
city-detail
"""

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CityList.urls'))
]

Projects/CityList/code/CityList/models.py
from django.db import models
from django.urls import reverse


class City(models.Model):
    # list of states
    States = (
        ('AL', 'Alabama'),
        ('AK', 'Alaska'),
        ('AZ', 'Arizona'),
        ('AR', 'Arkansas'),
        ('CA', 'California'),
        ('CO', 'Colorado'),
        ('CT', 'Connecticut'),
        ('DE', 'Delaware'),
        ('FL', 'Florida'),
        ('GA', 'Georgia'),
        ('HI', 'Hawaii'),
        ('ID', 'Idaho'),
        ('IL', 'Illinois'),
        ('IN', 'Indiana'),
        ('IA', 'Iowa'),
        ('KS', 'Kansas'),
        ('KY', 'Kentucky'),
        ('LA', 'Louisiana'),
        ('ME', 'Maine'),
        ('MD', 'Maryland'),
        ('MA', 'Massachusetts'),
        ('MI', 'Michigan'),
        ('MN', 'Minnesota'),
        ('MS', 'Mississippi'),
        ('MO', 'Missouri'),
        ('MT', 'Montana'),
        ('NE', 'Nebraska'),
        ('NV', 'Nevada'),
        ('NH', 'New Hampshire'),
        ('NJ', 'New Jersey'),
        ('NM', 'New Mexico'),
        ('NY', 'New York'),
        ('NC', 'North Carolina'),
        ('ND', 'North Dakota'),
        ('OH', 'Ohio'),
        ('OK', 'Oklahoma'),
        ('OR', 'Oregon'),
        ('PA', 'Pennsylvania'),
        ('RI', 'Rhode Island'),
        ('SC', 'South Carolina'),
        ('SD', 'South Dakota'),
        ('TN', 'Tennessee'),
        ('TX', 'Texas'),
        ('UT', 'Utah'),
        ('VT', 'Vermont'),
        ('VA', 'Virginia'),
        ('WA', 'Washington'),
        ('WV', 'West Virginia'),
        ('WI', 'Wisconsin'),
        ('WY', 'Wyoming')
    )
    name = models.CharField(max_length=200, default="Name", blank=False)
    is_active = models.BooleanField(default=False)
    website = models.URLField(max_length=200, blank=True)
    state = models.CharField(max_length=200, choices=States, blank=True)

    # Define default String to return the name for representing the Model object.
    def __str__(self):
        return self.name

    # Returns the URL to access a particular instance,
    # if you define this method then Django will automatically
    # add a "View on Site" button to the model's record editing screens in the Admin site
    def get_absolute_url(self):
        return reverse('city-details', args=[str(self.pk)])

Projects/CityList/code/CityList/forms.py
from django.forms import ModelForm
from .models import City


class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ['name', 'website', 'is_active', 'state', ]


"""
from django.forms import ModelForm
from .models import Project, Portfolio, Student
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# create class for project form
class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', ]


# create class for project form
class PortfolioForm(ModelForm):
    class Meta:
        model = Portfolio
        fields = ['title', 'contact_email', 'is_active', 'about', ]


# create class for project form
class CreateUserForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', ]


# create class for project form
class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'email', 'major', 'portfolio', ]
"""

Projects/CityList/code/CityList/views.py
import random
from django.views.generic import DetailView
from .forms import CityForm
from django.shortcuts import render
from .models import City


def index(request):
    # Retrieve a random city
    random_city = random.choice(City.objects.filter(is_active=True))

    context = {
        'random_city': random_city
    }
    return render(request, 'index.html', context)


def login(request):
    return render(request, 'login.html')


def logout(request):
    return render(request, 'logout.html')





def CityListView(request):
    context = {}
    form = CityForm()
    city_objects = City.objects.all()
    context['city'] = city_objects
    if request.method == 'POST':
        if 'save' in request.POST:
            print("Form is valid")
            form = CityForm(request.POST)
            if form.is_valid():
                form.save()
            else:
                print("Form is invalid")
        elif 'view' in request.POST:
            # Assuming 'view' is a button to view details of a specific city
            # Handle the view action here
            return render(request, 'city-details.html', context)
        elif 'delete' in request.POST:
            # Handle the delete action here
            pk = request.POST.get('delete')
            city = City.objects.get(id=pk)
            city.delete()

    elif request.method == 'GET':
        if 'view' in request.GET:
            # Assuming 'view' is a button to view details of a specific city
            # Handle the view action here
            return render(request, 'city-details.html', context)
        context['form'] = form

    return render(request, 'cities.html', context)


"""def CityDetailView(request, pk):
    # Retrieve the city instance or return a 404 error if not found
    city = get_object_or_404(City, id=pk)
    context = {
        'city': city
    }
    # form = CityForm(instance=city)
    return render(request, 'city-details.html', context)
"""


class CityDetailView(DetailView):
    model = City
    template_name = 'city-details.html'  # Specify the template name

Projects/CityList/code/templates/base_template.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
 <head>
   <title>UCCS CS Students</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
   <style>
     .nav-link {
       font-size: 20px; /* Set the font size to 20 pixels */
       font-weight: bold; /* Set the font weight to bold */
       border: 3px solid black; /* Add a border with 1px thickness and black color */
       border-radius: 5px; /* Add border radius for rounded corners */
       padding: 5px 10px; /* Add padding to space the text inside the button */
     }
   </style>
 </head>

 <body>
   <div class="container-fluid">

     <!-- Navbar-->
     <nav class="navbar navbar-expand-lg bg-warning navbar-light">
       <div class="container-fluid">
         <img src="{% static 'images/house_icon.png' %}">
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
           <div class="navbar-nav">
             <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
             <a class="nav-link" href="/cities">Cities</a>
             <a class="nav-link" href="#">Menu 3</a>
             {% if user.is_authenticated %}
               <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">Logout {{user}}</a>
             {% else %}
               <a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">Login</a>
             {% endif %}
           </div>
         </div>
       </div>
     </nav>

       <div class="col-sm-10">
         <!-- add block content to html template -->
         {% block content %}
         {% endblock %}
       </div>
     </div>
   </div>
 </body>
</html>

Projects/CityList/code/templates/cities.html
<!-- inherit from base_template.html-->
{% extends "base_template.html" %}
{%block tile%}
City List
{%endblock%}

<!-- Replace block content in base_template.html -->
{% block content %}

<form method="post" action="{% url 'cities' %}">
    <table>
        {% csrf_token %}
        <tr>
            <th>Name</th>
            <th>Website</th>
            <th>Active</th>
            <th>State</th>
            <th>Action</th>
        </tr>
        <tr>
            {% for field in form %}
            <td>{{ field }}</td>
            {% endfor %}
            <td><button class="btn btn-primary" name="save">Save</button></td> <!-- Use Bootstrap button class -->
        </tr>
        {% for city in city_objects %}
        <tr>
            <td>{{ city.name }}</td>
            <td>{{ city.state }}</td>
            <td>{{ city.is_active }}</td>
            <td>{{ city.website }}</td>
            <td>
                <a href="{% url 'edit-city' city.id %}" class="btn btn-primary">Edit</a> <!-- Edit button -->
                <a href="{% url 'delete-city' city.id %}" class="btn btn-danger">Delete</a> <!-- Delete button -->
                <a href="{% url 'city-details' city.id %}" class="btn btn-primary">Explore {{ city.name }}</a> <!-- City details button -->
            </td>
        </tr>
        {% endfor %}
    </table>
</form>

{% endblock %}

Projects/CityList/code/templates/city-details.html
<!-- inherit from base_template.html-->
{% extends "base_template.html" %}


<!-- Replace block content in base_template.html -->
{% block content %}
    <h1>City: {{ city.name }}</h1>
    <p><strong>State:</strong> {{ city.state }}</p>
    <p><strong>Active Status:</strong> {{ portfolio.is_active }}</p>
    <p><strong>Website:</strong> {{ city.website }}</p>



{% endblock %}

Projects/CityList/code/templates/index.html
{% extends 'base_template.html' %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col">
            <h1>Welcome to My Website!</h1>
            <p>This is an extremely basic home page.</p>

            <!-- Block featuring a random city -->
            <div class="card">
                <div class="card-header">
                    Featured City
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ random_city.name }}</h5>
                    <p class="card-text">State: {{ random_city.get_state_display }}</p>
                    <a href="{{ random_city.get_absolute_url }}" class="btn btn-primary">Explore {{ random_city.name }}</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Projects/CityList/code/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Projects/CityList/code/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>